name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types: completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          npm install
          npm run releaseArtifacts
